name: main

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  approve_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check user approval
        run: |
          if [[ "$GITLAB_USER_LOGIN" != "necto1328" ]]; then
            echo "User is not authorized to perform the merge."
            exit 1
          fi
          echo "User approved the merge."
