name: Manual workflow

on:
  push:
     branches: [ "dev", "main" ]
  pull_request:
     branches: [ "dev", "main" ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Check user approval
      run: |
        if [[ "${{ github.actor }}" != "necto12118" ]]; then
          echo "User not authorized to run this workflow."
          exit 1
        fi
