name: Manual workflow

on:
  merge:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Check user approval
      run: |
        if [[ "${{ github.actor }}" != "necto128" ]]; then
          echo "User not authorized to run this workflow."
          exit 1
        fi
